[workspace]
resolver = "2"
members = [
    "imports",
    "chapter1", 
    "chapter2",
    "chapter3",
    "chapter4",
    "chapter5",
    "chapter6",
    "chapter7",
    "chapter7/restaurant",
    "chapter7/restaurant-v2",
]
