[package]
name = "chapter7"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "restaurant_v2"
path = "restaurant_v2/src/lib.rs"

[dependencies]
